Repository ovh-ux/ng-ovh-telecom-universe-components, pull requests merged in 2018-12, with the labels that each got.

#25 feat(migration-ftth): check the current offer
  src/telecom/pack/migration/pack-migration-process.service.js
Labels: quality check ok

#29 docs(contributing): specify the right repository name
  CONTRIBUTING.md
Labels: enhancement

#26 feat(firmware): add firmware configuration into modem tab
  src/telecom/pack/xdsl/modem/pack-xdsl-modem-mediator.service.js
Labels: quality check ok

#36 Fix/migration ftth
  src/telecom/pack/migration/pack-migration-process.service.js
Labels: bug, quality check ok

#38 fix(resiliation): put in cache the resiliation modal
  src/resiliation/index.js
  src/resiliation/resiliation-reason.component.js
Labels: bug, quality check ok

#22 feat(telecom-voip): voip alias feature
  src/telecom/voip/index.js
  src/telecom/voip/service/alias/voip-service-alias.factory.js
  src/telecom/voip/service/alias/voip-service-alias.service.js
  src/telecom/voip/service/line/voip-service-line.service.js
  src/telecom/voip/service/voip-service.service.js
  src/telecom/voip/telecom-voip.constant.js
Labels: quality check ok

#45 feat(bankholidays): service to retrieve bank holidays for country, year
  src/bank-holidays/bank-holidays.constant.js
  src/bank-holidays/bank-holidays.service.js
  src/bank-holidays/index.js
  src/index.js
Labels: enhancement, quality check ok

#47 build(package.json): sort entries
  package.json
Labels: enhancement
