Repository ovh-ux/ng-ovh-telecom-universe-components, pull requests merged in 2019-01, with the labels that each got.

#55 fix(toasterror): add missing translation
  src/toast-error/index.js
  src/toast-error/toast-error.service.js
  src/toast-error/translations/Messages_fr_FR.xml
Labels: bug, translation required

#63 build(deps): upgrade ng-translate-async-loader to v2.0.0
  package.json
  rollup.config.js
  src/elapsed-time/index.js
  src/input-file/index.js
  src/ovh-password/index.js
  src/resiliation/index.js
  src/section-back-link/index.js
  src/shippingModeSelection/index.js
  src/telecom/retractation/index.js
  src/telecom/telephony/abbreviatedNumbers/index.js
  src/telecom/telephony/bulkAction/index.js
  src/telecom/telephony/callsFiltering/index.js
  src/toast-error/index.js
  src/toaster/index.js
  yarn.lock
Labels: enhancement

#68 fix: use same variable in js and html files for reason model
  src/resiliation/resiliation-reason.component.js
Labels: bug, quality check ok

#69 fix(resiliation): use the right binding for reason model
  src/resiliation/resiliation-reason.component.js
Labels: bug, quality check ok
